In [8]:
# Question 1
import numpy as np25
array = np25.array([[5,6,3],[15,7,3],[6,8,7]])

In [9]:
#Zero Array Q1.1
np25.zeros((3,4), dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [10]:
#Q1.2
print('Element in the second row and third column =', array[1][2])

Element in the second row and third column = 3


In [11]:
#Q1.3
for i in range(3):
    print('Max of Row', i+1, '=', np25.max(array[i]))

Max of Row 1 = 6
Max of Row 2 = 15
Max of Row 3 = 8


In [12]:
#Q1.4
for i in range(3):
    print('Mean of Row', i+1, '=',np25.mean(array[i]))

Mean of Row 1 = 4.666666666666667
Mean of Row 2 = 8.333333333333334
Mean of Row 3 = 7.0


In [13]:
#Q1.5
print('Subarray:')
for i in range(2):
    print(array[i])

Subarray:
[5 6 3]
[15  7  3]


In [14]:
#Q2
data = [5, 3, 7, 3, 3, 6, 19, 8, 4, 1]


In [15]:
#Mean
mean = np25.mean(data)
print('Mean =', mean)

Mean = 5.9


In [16]:
#Median
median = np25.median(data)
print('Median =', median)

Median = 4.5


In [17]:
#Mode
count = np25.unique(data, return_counts=True)
index = np25.argmax(count[1])
mode = (count[0])[index]
print('Mode =', mode)

Mode = 3


In [18]:
#Interquartile Range
sorted_data = np25.sort(data)
q1 = np25.percentile(sorted_data, 25)
q3 = np25.percentile(sorted_data, 75)
iqr=q3-q1
print('Interquartile Range =', iqr)

Interquartile Range = 3.75


In [19]:
#Outliers
l_bound = mean - iqr
u_bound = mean + iqr
key = 0
for i in data:
    if(data[i] > u_bound or data[i] < l_bound):
        print("Outlier Exists")
        key = 1
        break

if(key==0):
    print("Outlier Does Not Exist")

Outlier Exists


In [20]:
#Q3
import pandas as pd25
column = pd25.DataFrame({"":['Name', 'Age', 'Roll Number']})
print(column.head())

              
0         Name
1          Age
2  Roll Number


In [21]:
#Anagram
string_1 = input('String 1: ')
string_2 = input('String 2: ')

sort_str1 = sorted(string_1)
sort_str2 = sorted(string_2)

if(sort_str1 == sort_str2):
    print("Anagram")
else:
    print("Not Anagram")

String 1: rajas
String 2: raasj
Anagram
